### ISSUE TITLE
Sending hearders in the response doesn't work.

### ISSUE THREAD

**Issue by Mathiasduc** [pimterry/mockttp#7]
Hello, 

Thanks a lot for this great library it helped me a lot when writing test for our internal tooling,
but i recently got stuck when trying to send headers in the response. Here is the minimal reproducing case i came up with:

```javascript
import axios from 'axios';

const mockServer = require('mockttp').getLocal({ cors: true });

it('send a sucessfull request', async () => {
    const testHeaders = { Test: 'testValue' };
    const testData = 'many data';

    await mockServer.start();
    await mockServer.get('/test').thenReply(200, testData, testHeaders);

    const response = await axios.request({ method: 'get', url: mockServer.urlFor('/test') });
    expect(response.data).toEqual(testData);
    expect(response.headers).toEqual(testHeaders);
});

```
The first expect pass but the second doesn't

my version: `"mockttp": "^0.7.1",`

Did the PR https://github.com/pimterry/mockttp/pull/1 got broken ?
I tried to look into the source code, but did not found anything that seems to help me.
Isn't there a test that would test specifically that?
Should i write one?
I dont know typescript but i could try.
Thanks!

**Comment by pimterry** [comment]
I've done a little testing. It's actually not that the headers aren't set at all, it's that the name gets lowercased.

You can pretty much run the above directly in runkit: https://runkit.com/embed/h9yit04svd4c. If you run that and look at the result, you'll see some default & cors headers, but also `test: "testValue"` (rather than the `Test: "testValue"` that you're expecting).

Your test also won't work regardless, as you'll have the cors and other default headers included too (passing headers to `thenReply` just adds _extra_ headers), so you need to use some kind of loose matching instead, or check only against the specific headers that you're looking for.

Does the casing of headers matter to you? According to the HTTP spec itself, they're case-insensitive, but ofc there's an argument that the mock server should exactly match whatever you pass in regardless, in case you have some bizarre non-compliant client or something.

**Comment by Mathiasduc** [comment]
Ok this was all me...
I was not using the correct environement in jest (jsdom rather than node), i don't really know why, but setting the correct [environement](https://facebook.github.io/jest/docs/en/configuration.html#testenvironmentoptions-object) made the passing of headers work...
I did not need CORS, it was just making mockttp in jsdom * **facepalm** *. 
Sorry for wasting you time on this issue.
Should i close it?

**Comment by pimterry** [comment]
No problem, glad you got it sorted :+1:. Let me know if you have any other trouble!
